version: "3"

services:
  app:
    build:
      context: .
      dockerfile: app-dockerfile
      args:
        APP_NAME: example
        APP_VERSION: 1.0.0
    image: example_app
    ports:
      - 8080:80
    entrypoint: ./app-entrypoint.sh
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_INSTANCE: ${DATABASE_INSTANCE}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}

  db:
    build:
      context: .
      dockerfile: db-dockerfile
    image: example_db
    container_name: example_db
    ports:
      - 3036:3306
    environment:
      MYSQL_DATABASE: ${DATABASE_INSTANCE}
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
